name: FishMya Auto Miner

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/15 * * * *'  
  workflow_dispatch:  

jobs:
  run-miner:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: pip install -r requirements.txt
    
    - name: Run FishMya Miner
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        GAME_ACCESS_TOKEN: ${{ secrets.GAME_ACCESS_TOKEN }}
      run: python fishmya_bot.py
